## **실행 전에**

reversed_data_after_preprocessing.csv 추가

In [1]:
!git clone https://github.com/SOMJANG/Mecab-ko-for-Google-Colab

Cloning into 'Mecab-ko-for-Google-Colab'...
remote: Enumerating objects: 60, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 60 (delta 23), reused 20 (delta 5), pack-reused 0
Unpacking objects: 100% (60/60), done.


In [2]:
cd Mecab-ko-for-Google-Colab/

/content/Mecab-ko-for-Google-Colab


In [3]:
! bash install_mecab-ko_on_colab190912.sh

Installing konlpy.....
     |████████████████████████████████| 19.4MB 1.6MB/s 
     |████████████████████████████████| 92kB 9.1MB/s 
     |████████████████████████████████| 3.8MB 38.5MB/s 
  Found existing installation: tweepy 3.6.0
    Uninstalling tweepy-3.6.0:
      Successfully uninstalled tweepy-3.6.0
  Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
Done
Installing mecab-0.996-ko-0.9.2.tar.gz.....
from https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
--2020-08-29 13:08:40--  https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
Resolving bitbucket.org (bitbucket.org)... 18.205.93.1, 18.205.93.0, 18.205.93.2, ...
Connecting to bitbucket.org (bitbucket.org)|18.205.93.1|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://bbuseruploads.s3.amazonaws.com/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz?S

# 전처리

In [1]:
import pandas as pd
import csv
from tensorflow.keras.preprocessing.sequence import pad_sequences
from konlpy.tag import Mecab

In [5]:
cd ..

/content


In [49]:
data = pd.read_csv('/content/reversed_data_after_preprocessing.csv')
data

title                                            content
0                 서해상으로 북상 중인 태풍  바비  피해 줄이려면    Q  특히 농어촌에서 어떤 피해가 발생할지가 걱정인데요  Q  도심  집에 계신 ...
1          새벽 4시 5시 사이 서울 근접  이 시각 서울시 재난안전상황실   만약 이런 피해가 발생하면 가까운 구청 상황실이나 다산콜센터 등에 연락하시면 됩니...
2              코로나 때문에 봉사시간 못 채워    졸업 막힌 대학생들   정부 차원의 대책 마련이 필요하다는 의견도 나온다  코로나19라는 비상 상황인 만...
3           성인 남자가 서 있기 힘들 정도    태풍  바비  군산 도착  지금까지 전북 군산 비응항에서 YTN 김민성 입니다 이번 태풍  아무쪼록 큰 피해 ...
4             위험 반원  인천 초비상 초속 25m 넘으면 영종대교 통제  또 초속 25m 이상 바람이 불 경우 인천공항으로 향하는 영종대교와 인천대교 차량 ...
...                                        ...                                                ...
9370            깜깜이 감염  확진자 확산하는 원주시 다중이용시설 폐쇄      시는 전문 역학조사팀이 CCTV 확인과 카드 사용 조사 등 정밀한 역학조사를...
9371                  원주 코로나19 확진 잇달아 5명 추가 확진   도교육청은 오늘 원주교육지원청에서 원주권 유치원  초 중 고 특수학교 전체 비상교...
9372            경기 어제 신규확진 109명 코로나사태 이후 일일 최다      신규 확진자 중 감염 경로가 확인되지 않아  조사 중 으로 분류된 환자가 2...
9373  방역당국 사랑제일교회 밤샘대치    21일 명단확보 재시도 위해 대기 중  현재 방역당국 관계자들은 오전 9시 현재까지 현장에 남아 역학조사 재개를 위한 대기...
9374             사랑제일교회  밤샘 대치 속  교인 명단 제출  거부  방역당국은 사랑제일교회에 진입해 누락된 신도 명단과 최근 교회 방문자 명단 등을 확...

[9375 rows x 2 columns]

토큰화 + 불용어제거

In [138]:
encoder_input, decoder_input, decoder_output = [], [], []

In [139]:
mecab = Mecab()

# 불용어 정의
stopwords=['인데요','다','을','습니다','Q','이다','보인다','한다','했다','였다','이다','의','가','이','은','들','는','좀','잘','과','도','를','으로','자','에','와','하다']

for line in data['content']:
    temp = []
    temp = mecab.morphs(str(line))
    temp = [word for word in temp if not word in stopwords] # 불용어 제거
    encoder_input.append(temp)

In [140]:
for line in data['title']:
    temp = []
    temp.append('<start>')
    for word in mecab.morphs(str(line)):
      if word not in stopwords: # 불용어 제거
        temp.append(word) 
    decoder_input.append(temp)

In [141]:
for line in data['title']:
    temp = []
    for word in mecab.morphs(str(line)):
      if word not in stopwords: # 불용어 제거
        temp.append(word) 
    temp.append('<end>')
    decoder_output.append(temp)

In [142]:
print(encoder_input[:3])
print(decoder_input[:3])
print(decoder_output[:3])

[['특히', '농어촌', '에서', '어떤', '피해', '발생', '할지', '걱정', '도심', '집', '계신', '분', '어떻게', '대비', '해야', '합니까', '특히', '고층', '아파트', '유리창', '깨지', '피해', '태풍', '때', '종종', '발생', '했잖아요', '그때', '신문지', '붙인다', '든가', '테이프', '붙여', '놓', '으면', '예방', '되', '나요', '요즘', '창틀', '창틀', '사이', '헐거운', '부분', '고정', '하', '게', '중요', '하', '다고', '하', '던데', '태풍', '한창', '일', '때', '운전', '하', '지', '않', '게', '가장', '좋', '겠', '만', '어쩔', '수', '없이', '운전', '해야', '되', '경우', '있', '잖아요', '이럴', '때', '어떻게', '조심', '해야', '됩니까', '도심', '강풍', '피해', '로', '대표', '적', '간판', '떨어진다', '든가', '교회', '첨탑', '무너지', '경우', '있', '었', '이렇게', '서해', '상', '태풍', '올라오', '면', '주로', '어떤', '피해', '발생', '하', '나요', '이번', '바람', '피해', '강할', '것', '같', '강원', '대학교', '방재', '전문', '대학원', '김병식', '교수', '님', '모시', '고', '태풍', '피해', '어떻게', '대응', '해야', '하', '는지', '자세', '한', '얘기', '나눠', '보', '겠'], ['만약', '이런', '피해', '발생', '하', '면', '가까운', '구청', '상황실', '이나', '다산', '콜', '센터', '등', '연락', '하', '시', '면', '됩니다', '또', '정전', '피', '해도', '있', '수', '있', '공사장', '가림막', '이나', '현수막', '건물', '간판', '아파트', '

In [143]:
len(encoder_input)

9375

정수인코딩

In [144]:
import nltk
from nltk import FreqDist
import numpy as np

# 단어-빈도수 조합으로 이루어진 단어집합 해시맵 vocab을 생성한다.
# NLTK에서는 빈도수 계산 도구인 FreqDist()를 지원한다.
vocab = FreqDist(np.hstack(encoder_input))
print('단어 [코로나]의 빈도수는? ', vocab['코로나'], '번')

# most_common(N) : 가장 빈도수가 높은 N개의 단어를 반환
# 상위 1000000개의 단어만 보존
vocab = vocab.most_common(10000000)
vocab

단어 [코로나]의 빈도수는?  20367 번


[('하', 79298),
 ('고', 75329),
 ('있', 51628),
 ('한', 47168),
 ('했', 45838),
 ('일', 42887),
 ('에서', 41348),
 ('명', 38438),
 ('로', 30170),
 ('확진', 29167),
 ('것', 26675),
 ('등', 24314),
 ('코로나', 20367),
 ('적', 19750),
 ('지', 19539),
 ('해', 18436),
 ('받', 17099),
 ('19', 16417),
 ('수', 16166),
 ('기', 16072),
 ('2', 15276),
 ('인', 15099),
 ('되', 14764),
 ('1', 14594),
 ('면', 14140),
 ('할', 14078),
 ('않', 13385),
 ('시', 13371),
 ('됐', 13279),
 ('게', 13037),
 ('서울', 12756),
 ('교회', 12748),
 ('씨', 12686),
 ('3', 12332),
 ('며', 11963),
 ('까지', 11788),
 ('만', 11709),
 ('된', 11685),
 ('지난', 11661),
 ('었', 11525),
 ('방역', 11464),
 ('중', 11139),
 ('대', 10699),
 ('감염', 10534),
 ('검사', 10162),
 ('았', 10055),
 ('어', 9938),
 ('면서', 9157),
 ('라고', 9154),
 ('없', 9061),
 ('지역', 8803),
 ('다고', 8495),
 ('부터', 8486),
 ('.', 8356),
 ('전', 8319),
 ('월', 8291),
 ('집회', 8283),
 ('정부', 8061),
 ('발생', 7914),
 ('상황', 7872),
 ('관련', 7871),
 ('던', 7768),
 ('지만', 7631),
 ('권', 7624),
 ('말', 7539),
 ('환자', 7367),
 ('년',

In [145]:
word_to_index = {}

# 단어들에 순차적으로 1 ~ 까지의 인덱스를 부여한다
word_to_index = {word[0] : index + 1 for index, word in enumerate(vocab)}

# 특수 인덱스
word_to_index['unk'] = 0

encoded_input = []
for line in encoder_input:
  tmp = []
  for word in line:
    try:
      # 각 글자를 해당하는 정수로 변환한다.
      tmp.append(word_to_index[word])
    except KeyError: 
      # 단어 집합에 없는 단어일 경우(=빈도수 상위 100000 이외의 단어) unk로 대체된다.
      tmp.append(word_to_index['unk'])

  encoded_input.append(tmp)

# 기존의 리뷰가 성공적으로 encoding 되었는지 확인해보기
print(encoded_input[1])
print(len(encoded_input[1]))
print(len(data['content'][1]))

[1382, 275, 144, 59, 1, 25, 1535, 1133, 2010, 217, 16514, 2549, 296, 12, 896, 1, 28, 25, 574, 111, 2950, 1365, 843, 3, 19, 3, 3182, 6195, 217, 3126, 732, 1971, 686, 3598, 12, 313, 3805, 25, 134, 18045, 19, 3, 357, 1134, 1, 15, 27, 30, 257, 507, 2, 4293, 1, 30, 1, 618, 112, 604, 2369, 38, 732, 217, 3182, 881, 2206, 28, 30, 507, 493, 454, 721, 144, 3, 19, 3, 47, 449, 1, 2821, 1, 357, 187, 4053, 217, 5230, 115, 791, 1769, 1537, 217, 2005, 454, 10760, 19, 3, 52, 1272, 5, 71, 2328, 25, 201, 3448, 2230, 146, 26, 4901, 31, 1464, 7, 71, 1777, 4, 1726, 1060, 5168, 602, 127, 13513, 807, 87, 28, 25, 71, 2328, 173, 716, 31, 206, 475, 1094, 152, 3, 15, 27, 111, 187, 325, 2951, 22, 6480, 9427, 1192, 465, 1160, 122, 28, 53, 71, 2923, 26, 131, 36, 244, 214, 187, 119, 109, 1948, 3, 13, 18, 1179, 305, 345, 173, 98, 159, 28, 53, 95, 24, 28, 36, 4083, 14, 244, 1, 20, 9, 5, 413, 661, 38, 340, 144, 50, 63, 173, 716, 85, 28, 7, 90, 28, 457, 71, 31, 257, 4219, 15, 478, 60, 4336, 4021, 1, 2, 3, 127, 31, 802, 4

In [146]:
decoded_input = []
for line in decoder_input:
  tmp = []
  for word in line:
    try:
      # 각 글자를 해당하는 정수로 변환한다.
      tmp.append(word_to_index[word])
    except KeyError: 
      # 단어 집합에 없는 단어일 경우(=빈도수 상위 100000 이외의 단어) unk로 대체된다.
      tmp.append(word_to_index['unk'])

  decoded_input.append(tmp)

In [147]:
decoded_output = []
for line in decoder_output:
  tmp = []
  for word in line:
    try:
      # 각 글자를 해당하는 정수로 변환한다.
      tmp.append(word_to_index[word])
    except KeyError: 
      # 단어 집합에 없는 단어일 경우(=빈도수 상위 100000 이외의 단어) unk로 대체된다.
      tmp.append(word_to_index['unk'])

  decoded_output.append(tmp)

# 기존의 리뷰가 성공적으로 encoding 되었는지 확인해보기
print(encoded_input[0])
print(decoded_input[0])
print(decoded_output[0])
# print(len(encoded_input[0]))
# print(len(data['content'][0]))

[290, 6111, 7, 648, 144, 59, 1565, 741, 1579, 319, 3648, 123, 719, 449, 146, 7282, 290, 8667, 686, 3598, 5512, 144, 71, 131, 4900, 59, 11185, 1861, 7572, 23117, 9426, 4546, 5796, 673, 441, 740, 23, 2435, 2344, 5435, 5435, 457, 23118, 473, 2174, 1, 30, 539, 1, 52, 1, 7751, 71, 4184, 6, 131, 2355, 1, 15, 27, 30, 257, 507, 69, 37, 2997, 19, 410, 2355, 146, 23, 112, 3, 2138, 5008, 131, 719, 2230, 146, 8083, 1579, 454, 144, 9, 330, 14, 1971, 9163, 9426, 32, 7146, 3145, 112, 3, 40, 568, 999, 231, 71, 2345, 25, 1397, 648, 144, 59, 1, 2435, 166, 313, 144, 5572, 11, 115, 700, 1367, 6031, 915, 2046, 28181, 317, 551, 6112, 2, 71, 144, 719, 288, 146, 1, 479, 1543, 4, 885, 2009, 87, 69]
[0, 999, 231, 552, 42, 22, 71, 245, 144, 1370, 1771]
[999, 231, 552, 42, 22, 71, 245, 144, 1370, 1771, 0]


패딩

In [152]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
# maxlen 없어도 알아서 잘 패딩합니다

encoder_input = pad_sequences(encoded_input, padding="post")
decoder_input = pad_sequences(decoded_input, padding="post")
decoder_output = pad_sequences(decoded_output, padding="post")

In [153]:
print(encoder_input.shape)
print(decoder_input.shape)
print(decoder_output.shape)
print(encoder_input[:3])
print(decoder_input[:3])
print(decoder_output[:3])

(9375, 5441)
(9375, 25)
(9375, 25)
[[ 290 6111    7 ...    0    0    0]
 [1382  275  144 ...    0    0    0]
 [  58 1238  194 ...    0    0    0]]
[[   0  999  231  552   42   22   71  245  144 1370 1771    0    0    0
     0    0    0    0    0    0    0    0    0    0    0]
 [   0  716   85   28   90   28  457   31 1393 2142  187  287  281 2010
     0    0    0    0    0    0    0    0    0    0    0]
 [   0   13  135 2838  172  607 7977 2329 9198 3406    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0]]
[[ 999  231  552   42   22   71  245  144 1370 1771    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0]
 [ 716   85   28   90   28  457   31 1393 2142  187  287  281 2010    0
     0    0    0    0    0    0    0    0    0    0    0]
 [  13  135 2838  172  607 7977 2329 9198 3406    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0]]


테스트-트레인셋 분리

In [148]:
# 3:1로 나눴습니다
test_size = 3000 #위의 shape보고 결정할 것
encoder_input_train = encoder_input[:-test_size]
decoder_input_train = decoder_input[:-test_size]
decoder_output_train = decoder_output[:-test_size]

encoder_input_test = encoder_input[-test_size:]
decoder_input_test = decoder_input[-test_size:]
decoder_output_test = decoder_output[-test_size:]

# 학습

In [ ]:
from tensorflow.keras.layers import Input, LSTM, Embedding, Dense, Masking
from tensorflow.keras.models import Model

인코더

In [ ]:
encoder_inputs = Input(shape=(27,))
encoder_embed = Embedding(len(tokenizer_ko.word_index)+1, 50)(encoder_inputs)
encoder_mask = Masking(mask_value=0)(encoder_embed)
encoder_outputs, h_state, c_state = LSTM(50, return_state=True)(encoder_mask)

디코더

In [ ]:
decoder_inputs = Input(shape=(27,))
decoder_embed = Embedding(len(tokenizer_en.word_index)+1, 50)(decoder_inputs)
decoder_mask = Masking(mask_value=0)(decoder_embed)

decoder_lstm = LSTM(50, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(decoder_mask, initial_state=[h_state, c_state])
decoder_dense = Dense(len(tokenizer_en.word_index)+1, activation='softmax')
decoder_softmax_outputs = decoder_dense(decoder_outputs)

In [ ]:
model = Model([encoder_inputs, decoder_inputs], decoder_softmax_outputs)
model.compile(optimizer='rmsprop', loss='sparse_categorical_crossentropy', metrics=['acc'])
model.fit(x = [encoder_input_train, decoder_input_train], y = decoder_output_train, validation_data = ([encoder_input_test, decoder_input_test], decoder_output_test), batch_size = 128, epochs = 50)

# 예측

In [ ]:

encoder_model = Model(encoder_inputs, [h_state, c_state])

encoder_h_state = Input(shape=(50,))
encoder_c_state = Input(shape=(50,))
pd_decoder_outputs, pd_h_state, pd_c_state = decoder_lstm(decoder_mask, initial_state=[encoder_h_state, encoder_c_state])
pd_decoder_softmax_outputs = decoder_dense(pd_decoder_outputs)

decoder_model = Model([decoder_inputs] + [encoder_h_state, encoder_c_state], [pd_decoder_softmax_outputs] + [pd_h_state, pd_c_state])

In [ ]:
input_stc = input()
token_stc = input_stc.split()
encode_stc = tokenizer_ko.texts_to_sequences([token_stc])
pad_stc = pad_sequences(encode_stc, maxlen=27, padding="post")


states_value = encoder_model.predict(pad_stc)


predicted_seq = np.zeros((1,1))
predicted_seq[0, 0] = en_to_index['<start>']

decoded_stc = []

while True:
    output_words, h, c = decoder_model.predict([predicted_seq] + states_value)

    predicted_word = index_to_en[np.argmax(output_words[0,0])]  

    if predicted_word == '<end>':
        break

    decoded_stc.append(predicted_word)

    predicted_seq = np.zeros((1,1))
    predicted_seq[0, 0] = np.argmax(output_words[0,0])

    states_value = [h, c]

print(' '.join(decoded_stc))